USE DB_SP_SUP
GO

SELECT * FROM TB_M_DESTINATION
WHERE DESTINATION_CD_GT = '1212000'

EXEC USP_PART_CLAIM_AUTOFILL '1212000','08303561','B077VD','AH12PERV','0888083726'

DECLARE @Dest varchar(max) = '1212000',
@OrderNo varchar(max) = '08303561',
@InvoiceNo varchar(max) = 'B077VD',
@CaseNo varchar(max) = 'AH12PERV',
@PartNo varchar(max) = '0888083726'

SELECT ORI_DESTINATION_CODE AS DESTINATION_CODE
	,CUST_ORDER_NO AS ORDER_NO
	,PI_NO AS INVOICE_NO
	,SHIP_CASE_NO AS CASE_NO
	,SHIP_PNO AS PART_NO
	,DELIVERY_DATE	
	,tsa.ACTUAL_ARRIVAL_DT
	,a.SHIP_DOC_NO
	,tsa.SHIP_DOC_NO
	,SALES_PRICE
FROM
	DB_SP_WRH..TB_R_PROFORMA_INVOICE a
LEFT JOIN
	DB_SP_SUP..TB_R_TAM_SHIPMENT_ATA tsa
ON
	a.ORI_DESTINATION_CODE = ORI_DEST_CD AND a.SHIP_DOC_NO = tsa.SHIP_DOC_NO
WHERE
	tsa.SHIP_DOC_NO IS NOT NULL
	AND ORI_DESTINATION_CODE = @Dest
	AND a.CUST_ORDER_NO = @OrderNo
	AND a.PI_NO = @InvoiceNo
	AND a.SHIP_CASE_NO = @CaseNo
	AND a.SHIP_PNO = @PartNo
